# Docker Compose file Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  my_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./files:/usr/src/my_service/files
    env_file:
      - ./.env

networks:
  default:
    name: backend
